// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tl_update.proto

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	tl_update.proto

It has these top-level messages:
	Update
	ListenRequest
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mtp "github.com/cjongseok/mtproto/mtp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Update struct {
	// Types that are valid to be assigned to Value:
	//	*Update_Updates
	//	*Update_UpdatesDifference
	Value isUpdate_Value `protobuf_oneof:"Value"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isUpdate_Value interface {
	isUpdate_Value()
}

type Update_Updates struct {
	Updates *mtp.PredUpdates `protobuf:"bytes,1,opt,name=updates,oneof"`
}
type Update_UpdatesDifference struct {
	UpdatesDifference *mtp.PredUpdatesDifference `protobuf:"bytes,2,opt,name=updatesDifference,oneof"`
}

func (*Update_Updates) isUpdate_Value()           {}
func (*Update_UpdatesDifference) isUpdate_Value() {}

func (m *Update) GetValue() isUpdate_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Update) GetUpdates() *mtp.PredUpdates {
	if x, ok := m.GetValue().(*Update_Updates); ok {
		return x.Updates
	}
	return nil
}

func (m *Update) GetUpdatesDifference() *mtp.PredUpdatesDifference {
	if x, ok := m.GetValue().(*Update_UpdatesDifference); ok {
		return x.UpdatesDifference
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Update) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Update_OneofMarshaler, _Update_OneofUnmarshaler, _Update_OneofSizer, []interface{}{
		(*Update_Updates)(nil),
		(*Update_UpdatesDifference)(nil),
	}
}

func _Update_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Update)
	// Value
	switch x := m.Value.(type) {
	case *Update_Updates:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Updates); err != nil {
			return err
		}
	case *Update_UpdatesDifference:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UpdatesDifference); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Update.Value has unexpected type %T", x)
	}
	return nil
}

func _Update_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Update)
	switch tag {
	case 1: // Value.updates
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(mtp.PredUpdates)
		err := b.DecodeMessage(msg)
		m.Value = &Update_Updates{msg}
		return true, err
	case 2: // Value.updatesDifference
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(mtp.PredUpdatesDifference)
		err := b.DecodeMessage(msg)
		m.Value = &Update_UpdatesDifference{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Update_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Update)
	// Value
	switch x := m.Value.(type) {
	case *Update_Updates:
		s := proto.Size(x.Updates)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Update_UpdatesDifference:
		s := proto.Size(x.UpdatesDifference)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ListenRequest struct {
}

func (m *ListenRequest) Reset()                    { *m = ListenRequest{} }
func (m *ListenRequest) String() string            { return proto.CompactTextString(m) }
func (*ListenRequest) ProtoMessage()               {}
func (*ListenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Update)(nil), "proxy.Update")
	proto.RegisterType((*ListenRequest)(nil), "proxy.ListenRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UpdateStreamer service

type UpdateStreamerClient interface {
	ListenOnUpdates(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (UpdateStreamer_ListenOnUpdatesClient, error)
}

type updateStreamerClient struct {
	cc *grpc.ClientConn
}

func NewUpdateStreamerClient(cc *grpc.ClientConn) UpdateStreamerClient {
	return &updateStreamerClient{cc}
}

func (c *updateStreamerClient) ListenOnUpdates(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (UpdateStreamer_ListenOnUpdatesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UpdateStreamer_serviceDesc.Streams[0], c.cc, "/proxy.UpdateStreamer/ListenOnUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &updateStreamerListenOnUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UpdateStreamer_ListenOnUpdatesClient interface {
	Recv() (*Update, error)
	grpc.ClientStream
}

type updateStreamerListenOnUpdatesClient struct {
	grpc.ClientStream
}

func (x *updateStreamerListenOnUpdatesClient) Recv() (*Update, error) {
	m := new(Update)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for UpdateStreamer service

type UpdateStreamerServer interface {
	ListenOnUpdates(*ListenRequest, UpdateStreamer_ListenOnUpdatesServer) error
}

func RegisterUpdateStreamerServer(s *grpc.Server, srv UpdateStreamerServer) {
	s.RegisterService(&_UpdateStreamer_serviceDesc, srv)
}

func _UpdateStreamer_ListenOnUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdateStreamerServer).ListenOnUpdates(m, &updateStreamerListenOnUpdatesServer{stream})
}

type UpdateStreamer_ListenOnUpdatesServer interface {
	Send(*Update) error
	grpc.ServerStream
}

type updateStreamerListenOnUpdatesServer struct {
	grpc.ServerStream
}

func (x *updateStreamerListenOnUpdatesServer) Send(m *Update) error {
	return x.ServerStream.SendMsg(m)
}

var _UpdateStreamer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.UpdateStreamer",
	HandlerType: (*UpdateStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenOnUpdates",
			Handler:       _UpdateStreamer_ListenOnUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tl_update.proto",
}

func init() { proto.RegisterFile("tl_update.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0x87, 0x1b, 0x61, 0x1b, 0xbc, 0x32, 0xab, 0xc1, 0xc3, 0xe8, 0x49, 0x7a, 0xf2, 0x20, 0x89,
	0xcc, 0x9b, 0x47, 0xf1, 0x30, 0x64, 0xa0, 0x54, 0xf4, 0x2a, 0x5d, 0xf7, 0xae, 0x56, 0x9b, 0x3f,
	0x26, 0x6f, 0xc0, 0x7e, 0x06, 0xbf, 0xb4, 0x98, 0x54, 0x44, 0x3d, 0x25, 0xbc, 0x3c, 0xcf, 0x03,
	0x3f, 0xc8, 0xa9, 0x7f, 0x0a, 0x76, 0x5b, 0x13, 0x0a, 0xeb, 0x0c, 0x19, 0x3e, 0xb1, 0xce, 0xbc,
	0x0f, 0x85, 0x6c, 0x3b, 0x7a, 0x0e, 0x1b, 0xd1, 0x18, 0x25, 0x9b, 0x17, 0xa3, 0x5b, 0x8f, 0xe6,
	0x55, 0x2a, 0x8a, 0xd0, 0xd7, 0x2b, 0x69, 0xb0, 0xe8, 0x05, 0xf5, 0xc9, 0x2b, 0x3f, 0x18, 0x4c,
	0x1f, 0x62, 0x88, 0x9f, 0xc1, 0x2c, 0x25, 0xfd, 0x82, 0x9d, 0xb0, 0xd3, 0xfd, 0xe5, 0xa1, 0x50,
	0x64, 0xc5, 0x9d, 0xc3, 0x6d, 0x22, 0xfc, 0x2a, 0xab, 0xbe, 0x11, 0x7e, 0x03, 0x47, 0xe3, 0xf7,
	0xba, 0xdb, 0xed, 0xd0, 0xa1, 0x6e, 0x70, 0xb1, 0x17, 0xbd, 0xe2, 0xaf, 0xf7, 0x43, 0xac, 0xb2,
	0xea, 0xbf, 0x76, 0x35, 0x83, 0xc9, 0x63, 0xdd, 0x07, 0x2c, 0x73, 0x98, 0xaf, 0x3b, 0x4f, 0xa8,
	0x2b, 0x7c, 0x0b, 0xe8, 0x69, 0xb9, 0x86, 0x83, 0xd4, 0xb8, 0x27, 0x87, 0xb5, 0x42, 0xc7, 0x2f,
	0x21, 0x4f, 0xc8, 0xad, 0x1e, 0xeb, 0xfc, 0x58, 0xc4, 0xf1, 0xe2, 0x97, 0x5a, 0xcc, 0xc7, 0x6b,
	0xa2, 0xca, 0xec, 0x9c, 0x6d, 0xa6, 0x71, 0xf3, 0xc5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x02, 0xa8, 0x9f, 0x3e, 0x01, 0x00, 0x00,
}
